<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260404103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les livres, evenements, emprunts et inscriptions avec des donnees initiales pour BiblioConnect.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, category VARCHAR(120) NOT NULL, summary TEXT NOT NULL, cover_theme VARCHAR(120) NOT NULL, published_year INT NOT NULL, page_count INT NOT NULL, available_copies INT NOT NULL, featured BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBE5A331989D9B62 ON book (slug)');

        $this->addSql('CREATE TABLE library_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, speaker VARCHAR(255) NOT NULL, description TEXT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) NOT NULL, capacity INT NOT NULL, theme VARCHAR(120) NOT NULL, PRIMARY KEY(id))');

        $this->addSql('CREATE TABLE book_loan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, book_id INT NOT NULL, status VARCHAR(30) NOT NULL, reserved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, returned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF41CE2AA76ED395 ON book_loan (user_id)');
        $this->addSql('CREATE INDEX IDX_BF41CE2A16A2B381 ON book_loan (book_id)');

        $this->addSql('CREATE TABLE event_registration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, event_id INT NOT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_14A41907A76ED395 ON event_registration (user_id)');
        $this->addSql('CREATE INDEX IDX_14A4190771F7E88B ON event_registration (event_id)');

        $this->addSql('ALTER TABLE book_loan ADD CONSTRAINT FK_BF41CE2AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book_loan ADD CONSTRAINT FK_BF41CE2A16A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_registration ADD CONSTRAINT FK_14A41907A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_registration ADD CONSTRAINT FK_14A4190771F7E88B FOREIGN KEY (event_id) REFERENCES library_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
            INSERT INTO book (title, author, category, summary, cover_theme, published_year, page_count, available_copies, featured, slug, created_at) VALUES
            ('Architecture des Recits Numeriques', 'Ines Delcourt', 'Innovation', 'Un essai pratique sur la maniere de concevoir des experiences de lecture hybrides, entre ecran, salle de lecture et mediation culturelle.', 'sunrise', 2025, 248, 4, true, 'architecture-des-recits-numeriques', NOW()),
            ('Le Cartographe des Savoirs', 'Nassim El Amrani', 'Sciences humaines', 'Une traversee des reseaux de connaissances, des bibliotheques citoyennes et des lieux qui fabriquent du lien dans les villes contemporaines.', 'lagoon', 2023, 312, 2, true, 'le-cartographe-des-savoirs', NOW()),
            ('Frontend Editorial', 'Clara Vignal', 'Design', 'Un guide pointu pour penser les interfaces comme des objets editoriaux, avec rythme visuel, hierarchie typographique et narration.', 'ember', 2024, 196, 3, true, 'frontend-editorial', NOW()),
            ('Memoire des Quartiers', 'Sami Berrada', 'Societe', 'Recits, archives et methodes pour transmettre les memoires locales avec les habitants et les associations de terrain.', 'forest', 2022, 284, 5, false, 'memoire-des-quartiers', NOW()),
            ('Data Storytelling Public', 'Maya Laurent', 'Numerique', 'Des methodes concretes pour rendre les donnees lisibles, utiles et accessibles au grand public dans les institutions culturelles.', 'midnight', 2026, 221, 1, false, 'data-storytelling-public', NOW()),
            ('Bibliotheques en Mouvement', 'Pauline Richard', 'Culture', 'Une vision actuelle des bibliotheques comme tiers-lieux, plateformes de services et espaces de creation collective.', 'aurora', 2025, 265, 6, false, 'bibliotheques-en-mouvement', NOW())
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO library_event (title, speaker, description, starts_at, location, capacity, theme) VALUES
            ('Rencontre auteur: creer une bibliotheque vivante', 'Leila Messaoudi', 'Une conversation sur les collections qui evoluent avec les usages, suivie d''un temps de questions avec le public.', '2026-04-12 18:30:00', 'Auditorium principal', 80, 'copper'),
            ('Atelier UX pour espaces culturels', 'Julien Morel', 'Un atelier intensif pour penser parcours usagers, signaletique et experience numerique de la mediatheque.', '2026-04-18 14:00:00', 'Studio collaboratif', 24, 'teal'),
            ('Club lecture: futurs desirables', 'Sarah El Hamdi', 'Un cercle de lecture consacre aux essais et fictions qui imaginent des villes plus sobres, plus ouvertes et plus cooperatives.', '2026-04-25 17:00:00', 'Salon des periodiques', 30, 'gold')
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE event_registration DROP CONSTRAINT FK_14A41907A76ED395');
        $this->addSql('ALTER TABLE event_registration DROP CONSTRAINT FK_14A4190771F7E88B');
        $this->addSql('ALTER TABLE book_loan DROP CONSTRAINT FK_BF41CE2AA76ED395');
        $this->addSql('ALTER TABLE book_loan DROP CONSTRAINT FK_BF41CE2A16A2B381');
        $this->addSql('DROP TABLE event_registration');
        $this->addSql('DROP TABLE book_loan');
        $this->addSql('DROP TABLE library_event');
        $this->addSql('DROP TABLE book');
    }
}
