<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260406113921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE book_favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_713A9880A76ED395 ON book_favorite (user_id)');
        $this->addSql('CREATE INDEX IDX_713A988016A2B381 ON book_favorite (book_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_book_favorite_user_book ON book_favorite (user_id, book_id)');
        $this->addSql('CREATE TABLE book_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating SMALLINT NOT NULL, comment TEXT NOT NULL, is_approved BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50948A4BA76ED395 ON book_review (user_id)');
        $this->addSql('CREATE INDEX IDX_50948A4B16A2B381 ON book_review (book_id)');
        $this->addSql('ALTER TABLE book_favorite ADD CONSTRAINT FK_713A9880A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book_favorite ADD CONSTRAINT FK_713A988016A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book_review ADD CONSTRAINT FK_50948A4BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book_review ADD CONSTRAINT FK_50948A4B16A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book ADD language VARCHAR(80) DEFAULT \'Francais\'');
        $this->addSql('UPDATE book SET language = \'Francais\' WHERE language IS NULL');
        $this->addSql('ALTER TABLE book ALTER COLUMN language SET NOT NULL');
        $this->addSql('ALTER TABLE book ALTER COLUMN language DROP DEFAULT');
        $this->addSql('ALTER TABLE book ADD image_url VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE book_loan ADD scheduled_for TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE book_favorite DROP CONSTRAINT FK_713A9880A76ED395');
        $this->addSql('ALTER TABLE book_favorite DROP CONSTRAINT FK_713A988016A2B381');
        $this->addSql('ALTER TABLE book_review DROP CONSTRAINT FK_50948A4BA76ED395');
        $this->addSql('ALTER TABLE book_review DROP CONSTRAINT FK_50948A4B16A2B381');
        $this->addSql('DROP TABLE book_favorite');
        $this->addSql('DROP TABLE book_review');
        $this->addSql('ALTER TABLE book DROP language');
        $this->addSql('ALTER TABLE book DROP image_url');
        $this->addSql('ALTER TABLE book_loan DROP scheduled_for');
        $this->addSql('ALTER INDEX idx_dc4e460b16a2b381 RENAME TO idx_bf41ce2a16a2b381');
        $this->addSql('ALTER INDEX idx_dc4e460ba76ed395 RENAME TO idx_bf41ce2aa76ed395');
        $this->addSql('ALTER INDEX idx_8fbbad54a76ed395 RENAME TO idx_14a41907a76ed395');
        $this->addSql('ALTER INDEX idx_8fbbad5471f7e88b RENAME TO idx_14a4190771f7e88b');
    }
}
